### PR TITLE
added navigation buttons to player headline on player stats page

### PR DESCRIPTION
**Pull request by imkunet**
im popping off bro
image

### CODE REVIEW

**Comment by imkunet** [comment]
this feature is useful because the top search bar brings you to this page and if you wish to access these pages for a player you have to go to the homepage and then type in their name and then go to the desired page

**Comment by amosyu2000** [comment]
Actually, you don't need to go back to the homepage. You can click on "Achievement Points", "Quests", "Friends", or "Guild" on the player's left-hand card to quickly navigate between different pages.

**Comment by imkunet** [comment]
huh I didn't notice this, guess this PR is completely redundant. thanks!

**Comment by amosyu2000** [comment]
Similarly, you could type "arena_1v1 q" in the top searchbar and it will bring you to the quests page for that player. Works all the same with "g" for guild, "f" for friends, etc. Maybe I should make that more clear on my site.

**Comment by imkunet** [comment]
I think a great place to put it is in the tips on the frontpage.

**Pull request closed without merging**
